[versions]
agp = "8.4.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
amapLocation = "4.5.0"
material = "1.10.0"
biometric = "1.1.0"
securityCrypto = "1.1.0-alpha06"
playServicesAuth = "21.2.0"
lifecycleRuntime = "2.8.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
amap-location = { group = "com.amap.api", name = "location-aar", version.ref = "amapLocation" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycleRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

